[project]
name = "sparql-rag-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain>=0.3.19",
    "langchain-together>=0.3.0",
    "langgraph>=0.2.74",
]
